global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "snmp"
    static_configs:
      - targets:
          - 192.168.20.1 # SNMP Mikrotik UKI
          - 16.72.20.1 # SNMP Device 2
    metrics_path: /snmp
    params:
      module: [mikrotik]
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116 # The SNMP exporter's real hostname:port.

 # Global exporter-level metrics
  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['snmp-exporter:9116']
  
  
